### PR TITLE
Update cfbtn.js.es6

### LINKED ISSUE #4: Missing toolbar icon in recent versions of Discourse
The toolbar icon "file-code-o" is not available in Discourse anymore since they [switched to SVG icons ](https://meta.discourse.org/t/introducing-font-awesome-5-and-svg-icons/101643) in version 2.2.0

Bundled icons can be found [here](https://github.com/discourse/discourse/blob/6d2708c3fb1e59db762dd85aa33b4e21061b7017/lib/svg_sprite/svg_sprite.rb)

### PR DESCRIPTION
**Pull request by danielbomconselho**
Resolves #4 

Update icons from fontawsome 4 to 5.

### CODE REVIEW

**Comment by daniel-cabral** [comment]
Hey @ThomDietrich !

**Comment by ThomDietrich** [comment]
Awesome! In the end it was so easy :)

**Comment by daniel-cabral** [comment]
Oh Yeah! I'll update our forum tonight! Thank you!

**Comment by daniel-cabral** [comment]
And thanks @danielbomconselho !

**Comment by ThomDietrich** [comment]
@daniel-cabral https://meta.discourse.org/t/code-fences-highlighting-buttons-plugin/46661

Please let me know when you were able to update the plugin and you are seeing the icons

**Comment by daniel-cabral** [comment]
@ThomDietrich , I've restarted our forum to force a git pull on repo but the old icon stay in the code. Did you merge to master?

**Comment by ThomDietrich** [comment]
Check if you are seeing version 0.6.0 installed on your system. I did just create a git tag, see if that triggers the update.
https://github.com/ThomDietrich/discourse-plugin-code-fences-buttons/tags

**Pull request merged**
